routes/web.php
<?php

use App\Http\Livewire\Auth\LoginLivewire;
use App\Http\Livewire\Auth\RegisterLivewire;
use App\Http\Livewire\Auth\PasswordResetLivewire;
use App\Http\Livewire\Auth\ForgotPasswordLivewire;

use App\Http\Livewire\BannerLivewire;
use App\Http\Livewire\DashboardLivewire;
use App\Http\Livewire\CategoryLivewire;
use App\Http\Livewire\SubCategoryLivewire;
use App\Http\Livewire\VendorTypeLivewire;
use App\Http\Livewire\VendorLivewire;
use App\Http\Livewire\ProductLivewire;
use App\Http\Livewire\FavouriteLivewire;
use App\Http\Livewire\ReviewLivewire;
use App\Http\Livewire\OptionGroupLivewire;
use App\Http\Livewire\MenuLivewire;
use App\Http\Livewire\OptionLivewire;
use App\Http\Livewire\WalletTransactionLivewire;

use App\Http\Livewire\ServiceLivewire;

use App\Http\Livewire\OrderLivewire;
use App\Http\Livewire\CouponLivewire;
use App\Http\Livewire\CouponReportLivewire;
use App\Http\Livewire\DeliveryAddressLivewire;

use App\Http\Livewire\CurrencyLivewire;
use App\Http\Livewire\AppSettingsLivewire;
use App\Http\Livewire\WebsiteSettingsLivewire;
use App\Http\Livewire\ServerSettingsLivewire;
use App\Http\Livewire\SettingsLivewire;
use App\Http\Livewire\PaymentMethodivewire;
use App\Http\Livewire\VendorPaymentMethodLivewire;
use App\Http\Livewire\Payment\OrderPaymentLivewire;
use App\Http\Livewire\Payment\OrderPaymentCallbackLivewire;

use App\Http\Livewire\PackageTypeLivewire;
use App\Http\Livewire\PackageTypePricingLivewire;
use App\Http\Livewire\CountryLivewire;
use App\Http\Livewire\StateLivewire;
use App\Http\Livewire\CitiesLivewire;
use App\Http\Livewire\VendorCitiesLivewire;
use App\Http\Livewire\VendorStatesLivewire;
use App\Http\Livewire\VendorCountriesLivewire;

use App\Http\Livewire\UserLivewire;
use App\Http\Livewire\DriverLivewire;
use App\Http\Livewire\DriverEarningLivewire;
use App\Http\Livewire\DriverRemittanceLivewire;
use App\Http\Livewire\VendorEarningLivewire;
use App\Http\Livewire\PayoutLivewire;

use App\Http\Livewire\BackUpLivewire;
use App\Http\Livewire\DataLivewire;
use App\Http\Livewire\NotificationLivewire;
use App\Http\Livewire\TranslationLivewire;
use App\Http\Livewire\ImportLivewire;
use App\Http\Livewire\UpgradeLivewire;
use App\Http\Livewire\SMSGatewayLivewire;
use App\Http\Livewire\ExtensionLivewire;
use App\Http\Livewire\CronJobLivewire;
use App\Http\Livewire\AutoAssignmentLivewire;

use App\Http\Livewire\Payment\WalletTopUpLivewire;
use App\Http\Livewire\Payment\WalletTopUpCallbackLivewire;

use App\Http\Livewire\SubscriptionLivewire;
use App\Http\Livewire\SubscribeLivewire;
use App\Http\Livewire\MySubscriptionLivewire;
use App\Http\Livewire\VendorSubscriptionLivewire;
use App\Http\Livewire\Payment\SubscribeCallbackLivewire;

use App\Http\Livewire\ProfileLivewire;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//
use App\Http\Livewire\VehicleTypeLivewire;
use App\Http\Livewire\VehicleLivewire;
use App\Http\Livewire\CarMakeLivewire;
use App\Http\Livewire\CarModelLivewire;
use App\Http\Livewire\PaymentMethodVehicleTypeLivewire;
use App\Http\Livewire\TaxiSettingLivewire;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web']], function () {

    // Auth
    Route::get('login', LoginLivewire::class)->name('login');
    Route::get('register', RegisterLivewire::class)->name('register');
    Route::get('logout', function () {
        Auth::logout();
        return redirect()->route('login');
    })->name('logout');

    Route::get('password/forgot', ForgotPasswordLivewire::class)->name('password.forgot');
    Route::get('password/update/{code}/{email}', PasswordResetLivewire::class)->name('password.reset.link');


    // Pages
    Route::get('privacy/policy', function () {
        return view('layouts.pages.privacy');
    })->name('privacy');

    Route::get('pages/contact', function () {
        return view('layouts.pages.contact');
    })->name('contact');

    Route::get('pages/terms', function () {
        return view('layouts.pages.terms');
    })->name('terms');

    // AUth routes
    Route::group(['middleware' => ['auth']], function () {

        //
        Route::get('profile', ProfileLivewire::class)->name('profile');
        Route::get('', DashboardLivewire::class)->name('dashboard');
        Route::get('product/products', ProductLivewire::class)->name('products');
        Route::get('product/menus', MenuLivewire::class)->name('products.menus');
        Route::get('product/options/group', OptionGroupLivewire::class)->name('products.options.group');
        Route::get('product/options', OptionLivewire::class)->name('products.options');

        //services 
        Route::get('service/services', ServiceLivewire::class)->name('services');

        Route::get('order/orders', OrderLivewire::class)->name('orders');
        Route::get('coupons', CouponLivewire::class)->name('coupons');
        Route::get('coupons/report', CouponReportLivewire::class)->name('coupons.report');

        Route::get('vendor/types', VendorTypeLivewire::class)->name('vendor.types');
        Route::get('vendors', VendorLivewire::class)->name('vendors');

        //admin/manager routes
        Route::get('earnings/drivers', DriverEarningLivewire::class)->name('earnings.drivers');
        Route::get('earnings/remittance', DriverRemittanceLivewire::class)->name('earnings.remittance');
        Route::get('payouts', PayoutLivewire::class)->name('payouts');


        //admin routes
        Route::group(['middleware' => ['role:admin']], function () {

            //
            Route::get('operations/cron/job', CronJobLivewire::class)->name('configure.cron.job');
            Route::get('operations/order/assignment', AutoAssignmentLivewire::class)->name('auto.assignments');
            Route::get('banners', BannerLivewire::class)->name('banners');
            Route::get('categories', CategoryLivewire::class)->name('categories');
            Route::get('categories/subcategories', SubCategoryLivewire::class)->name('subcategories');
            Route::get('product/favourites', FavouriteLivewire::class)->name('favourites');
            Route::get('reviews', ReviewLivewire::class)->name('reviews');
            // Route::get('order/delivery/addresses', DeliveryAddressLivewire::class)->name('delivery.addresses');

            Route::get('wallet/transactions', WalletTransactionLivewire::class)->name('wallet.transactions');
            //
            Route::get('setting/currencies', CurrencyLivewire::class)->name('currencies');
            Route::get('setting/settings', SettingsLivewire::class)->name('settings');
            Route::get('setting/app/settings', AppSettingsLivewire::class)->name('settings.app');
            Route::get('setting/website/settings', WebsiteSettingsLivewire::class)->name('settings.website');
            Route::get('setting/app/server', ServerSettingsLivewire::class)->name('settings.server');
            Route::get('setting/payment/methods', PaymentMethodivewire::class)->name('payment.methods');
            Route::get('setting/translation', TranslationLivewire::class)->name('translation');
            Route::get('setting/upgrade', UpgradeLivewire::class)->name('upgrade');
            Route::get('notification/send', NotificationLivewire::class)->name('notification.send');
            
            //package
            Route::get('package/types', PackageTypeLivewire::class)->name('package.types');
            Route::get('package/countries', CountryLivewire::class)->name('package.countries');
            Route::get('package/states', StateLivewire::class)->name('package.states');
            Route::get('package/cities', CitiesLivewire::class)->name('package.cities');
            
            
            //imports
            Route::get('operations/imports', ImportLivewire::class)->name('imports');
            Route::get('operations/backup', BackUpLivewire::class)->name('backups');
            Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');
            Route::get('operations/data/clear', DataLivewire::class)->name('data.clear');

            //settings
            Route::get('setting/sms/gateways', SMSGatewayLivewire::class)->name('sms.settings');
            //subscription
            Route::get('subscription/subscriptions', SubscriptionLivewire::class)->name('subscriptions');
            
            //Taxi booking
            Route::get('taxi/vehicle/types', VehicleTypeLivewire::class)->name('taxi.vehicle.types');
            Route::get('taxi/vehicles', VehicleLivewire::class)->name('taxi.vehicles');
            Route::get('taxi/car/makes', CarMakeLivewire::class)->name('taxi.car.makes');
            Route::get('taxi/car/models', CarModelLivewire::class)->name('taxi.car.models');
            Route::get('taxi/payment/methods', PaymentMethodVehicleTypeLivewire::class)->name('taxi.payment.methods');
            Route::get('taxi/settings', TaxiSettingLivewire::class)->name('taxi.settings');
        });
        
        Route::group(['middleware' => ['role:admin|city-admin']], function () {
            
            Route::get('users', UserLivewire::class)->name('users');
            Route::get('order/delivery/addresses', DeliveryAddressLivewire::class)->name('delivery.addresses');
            Route::get('earnings/vendors', VendorEarningLivewire::class)->name('earnings.vendors');
            Route::get('extensions', ExtensionLivewire::class)->name('extensions');

            //subscription
            Route::get('subscription/vendors/subscriptions', VendorSubscriptionLivewire::class)->name('vendors.subscriptions');
            

        });

        //manager routes

app/Models/Order.php
<?php

namespace App\Models;

use App\Traits\FirebaseMessagingTrait;
use App\Traits\FirebaseDBTrait;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Spatie\ModelStatus\HasStatuses;
use Illuminate\Support\Facades\Schema;

class Order extends BaseModel
{

    use FirebaseMessagingTrait, FirebaseDBTrait;
    use HasStatuses;


    protected $fillable = ["note", "reason", "sub_total", "total", "driver_id", "delivery_fee"];
    protected $with = ["user", "driver", 'statuses', 'stops', 'order_service', 'taxi_order'];
    protected $appends = ["payment_link", 'formatted_date', 'type', 'formatted_type', 'can_rate', 'can_rate_driver', 'status', 'pickup_location', 'dropoff_location', 'photo'];


    public function scopeFullData($query)
    {
        return $query->with(["products.product", "stops.delivery_address", "user", "driver", "delivery_address", "payment_method", "vendor" => function ($query) {
            return $query->withTrashed();
        }, 'package_type']);
    }

    public function scopeMine($query)
    {
        return $query->when(Auth::user()->hasRole('manager'), function ($query) {
            return $query->where('vendor_id', Auth::user()->vendor_id);
        })->when(Auth::user()->hasRole('city-admin'), function ($query) {
            return $query->whereHas('vendor', function ($query) {
                return $query->where('creator_id', Auth::id());
            });
        });
    }

    public function products()
    {
        return $this->hasMany('App\Models\OrderProduct', 'order_id', 'id');
    }

    public function stops()
    {
        return $this->hasMany('App\Models\OrderStop', 'order_id', 'id')->withTrashed();
    }

    public function order_service()
    {
        return $this->belongsTo('App\Models\OrderService', 'id', 'order_id');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'id');
    }

    public function driver()
    {
        return $this->belongsTo('App\Models\User', 'driver_id', 'id');
    }

    public function delivery_address()
    {
        return $this->belongsTo('App\Models\DeliveryAddress', 'delivery_address_id', 'id');
    }

    public function payment_method()
    {
        return $this->belongsTo('App\Models\PaymentMethod', 'payment_method_id', 'id');
    }

    public function vendor()
    {
        return $this->belongsTo('App\Models\Vendor', 'vendor_id', 'id');
    }

    public function payment()
    {
        return $this->belongsTo('App\Models\Payment', 'id', 'order_id');
    }

    public function taxi_order()
    {
        return $this->hasOne('App\Models\TaxiOrder', 'order_id', 'id');
    }


    //
    public function package_type()
    {
        return $this->belongsTo('App\Models\PackageType', 'package_type_id', 'id');
    }

    public function auto_assignment()
    {
        return $this->hasOne('App\Models\AutoAssignment', 'order_id', 'id')->where('status', "pending");
    }

    public function getPickupLocationAttribute()
    {
        if (count($this->stops) > 0) {
            return $this->stops->first()->delivery_address;
        } else {
            return null;
        }
    }

    public function getDropoffLocationAttribute()
    {
        if (count($this->stops) > 1) {
            return $this->stops->last()->delivery_address;
        } else {
            return null;
        }
    }

    public function getTypeAttribute()
    {
        return $this->vendor->vendor_type->slug ?? '';
    }




    //
    public function getCanRateAttribute()
    {

        if (empty(Auth::user())) {
            return false;
        }
        //
        $vendorReview = Review::where('user_id', Auth::id())->where('order_id', $this->id)->first();
        return empty($vendorReview);
    }

    public function getCanRateDriverAttribute()
    {

        if (empty(Auth::user())) {
            return false;
        }
        //
        $driverReview = Review::where('user_id', Auth::id())->where('driver_id', $this->driver_id)->first();
        return empty($driverReview);
    }

    public function getPaymentLinkAttribute()
    {

        if ($this->payment_status == "pending") {
            return route('order.payment', ["code" => $this->code]);
        } else {
            return "";
        }
    }

    //TODO
    public function getFormattedTypeAttribute()
    {
        return Str::ucfirst($this->vendor->vendor_type->name ?? '');
    }
    public function getIsPackageAttribute()
    {
        return ($this->vendor->vendor_type->slug ?? '') == "package";
    }

    public function getIsFoodAttribute()
    {
        return in_array(($this->vendor->vendor_type->slug ?? ''), ["food", "grocery", "pharmacy"]);
    }

    public function getOrderTypeAttribute()
    {
        if (empty($this->vendor)) {
            return "taxi";
        }
        //
        return $this->vendor->vendor_type->slug;
    }



    //updating wallet balance is order failed and was paid via wallet
    public function refundUser()
    {
        //'pending','preparing','ready','enroute','delivered','failed','cancelled'
        if (in_array($this->status, ['failed', 'cancelled']) && in_array($this->payment_status, ['successful'])  && $this->payment_method->slug != "cash") {

            //update user wallet
            $wallet = Wallet::firstOrCreate(
                ['user_id' => $this->user_id],
                ['balance' => 0]
            );

            //
            $wallet->balance += $this->total;
            $wallet->save();

            //save wallet transactions
            $walletTransaction = new WalletTransaction();
            $walletTransaction->wallet_id = $wallet->id;
            $walletTransaction->amount = $this->total;
            $walletTransaction->reason = "Refund";
            $walletTransaction->status = "successful";
            $walletTransaction->is_credit = 1;
            $walletTransaction->save();
        }
    }
}

app/Http/Livewire/AutoAssignmentLivewire.php
<?php

namespace App\Http\Livewire;

use GeoSot\EnvEditor\Facades\EnvEditor;

class AutoAssignmentLivewire extends BaseLivewireComponent
{

    public $cronJobKey;


    public function render()
    {
        if (empty($this->cronJobKey)) {
            $this->cronJobKey = env("CRON_JOB_KEY", "");
        }
        return view('livewire.auto-assignment');
    }


    public function genNewKey()
    {

        $this->cronJobKey = \Str::random(32);
        if (EnvEditor::keyExists("CRON_JOB_KEY")) {
            EnvEditor::editKey("CRON_JOB_KEY", "'" . $this->cronJobKey . "'");
        } else {
            EnvEditor::addKey("CRON_JOB_KEY", "'" . $this->cronJobKey . "'");
        }
    }
}

app/Http/Livewire/CronJobLivewire.php
<?php

namespace App\Http\Livewire;

use GeoSot\EnvEditor\Facades\EnvEditor;

class CronJobLivewire extends BaseLivewireComponent
{

    public $cronJobKey;


    public function render()
    {
        if (empty($this->cronJobKey)) {
            $this->cronJobKey = env("CRON_JOB_KEY", "");
        }
        return view('livewire.cron-job');
    }


    public function genNewKey()
    {

        $this->cronJobKey = \Str::random(32);
        if (EnvEditor::keyExists("CRON_JOB_KEY")) {
            EnvEditor::editKey("CRON_JOB_KEY", "'" . $this->cronJobKey . "'");
        } else {
            EnvEditor::addKey("CRON_JOB_KEY", "'" . $this->cronJobKey . "'");
        }
    }
}

resources/views/livewire/order/package_order_details.blade.php
<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
    <x-details.item title="{{ __('Code') }}"
        text="#{{ $selectedModel->code ?? '' }}" />
    <x-details.item title="{{ __('Status') }}"
        text="{{ $selectedModel->status ?? '' }}" />
    <x-details.item title="{{ __('Payment Status') }}"
        text="{{ $selectedModel->payment_status ?? '' }}" />
    <x-details.item title="{{ __('Payment Method') }}"
        text="{{ $selectedModel->payment_method->name ?? '' }}" />
</div>
<div class="grid grid-cols-1 gap-4 mt-5 border-t md:grid-cols-2 lg:grid-cols-3">
    <x-details.item
        title="{{ $selectedModel != null && $selectedModel->is_package ? __('Sender')  : __('User') }}"
        text="{{ $selectedModel->user->name ?? '' }}" />
    <x-details.item
        title="{{ $selectedModel != null && $selectedModel->is_package ? __('Sender Phone')  : __('User Phone') }}"
        text="{{ $selectedModel->user->phone ?? '' }}" />

</div>
{{-- recipient address/info --}}
<div class="grid grid-cols-1 gap-4 md:grid-cols-2">

    @foreach($selectedModel->stops as $key => $stop)
        <x-details.item title="{{ __('Stop') }} {{ $key + 1 }}"
            text="{{ $stop->delivery_address->address ?? '' }}" />
            <x-details.item title="{{ __('Recipient') }}">
                {{ $stop->name ?? '' }}
                @empty($stop->phone)
                    
                @else 
                    ({{ $stop->phone ?? '' }})
                @endempty
                 
            </x-details.item>
    @endforeach

</div>
<div class="grid grid-cols-1 gap-4 mt-5 border-t md:grid-cols-2 lg:grid-cols-3">

    <x-details.item title="{{ __('Vendor') }}"
        text="{{ $selectedModel->vendor->name ?? '' }}" />
    <x-details.item title="{{ __('Vendor Address') }}"
        text="{{ $selectedModel->vendor->address ?? '' }}" />


    <x-details.item title="{{ __('Date of order') }}"
        text="{{ $selectedModel != null ? $selectedModel->created_at->format('M d, Y \\a\\t H:i a') : '' }}" />
    <x-details.item title="{{ __('Updated At') }}"
    text="{{ $selectedModel != null ? $selectedModel->updated_at->format('M d, Y \\a\\t H:i a') : '' }}" />
</div>

{{-- driver info --}}
<div class="grid grid-cols-1 gap-4 pt-4 mt-4 border-t md:grid-cols-2 lg:grid-cols-3">
    <x-details.item title="{{ __('Driver') }}"
        text="{{ $selectedModel->driver->name ?? '--' }}" />
    <x-details.item title="{{ __('Driver Phone') }}"
        text="{{ $selectedModel->driver->phone ?? '--' }}" />
</div>

{{-- parcel details --}}
<div class="pt-4 mt-4 border-t ">
    <x-order.package :order="$selectedModel ?? ''" />
</div>

{{-- order photo --}}
@if($selectedModel != null && $selectedModel->photo && !strpos($selectedModel->photo, 'default.png') )
<p class="mt-8 font-bold text-md">Order Photo</p>
    <a href="{{ $selectedModel->photo }}" target="_blank"> <img src="{{ $selectedModel->photo }}" class="w-56 h-56 rounded-sm" /></a>
@endif

{{-- money --}}
<div class="pt-4 border-t justify-items-end">

    <div class="flex items-center justify-start p-4 space-x-20 border-2">
        <p class="my-auto">
            {{-- <x-label title="Driver Tip" /> --}}
            {{ __('Driver Tip') }}
        </p>
        <x-details.p
            text="{{ setting('currency', '$') }}{{ $selectedModel->tip ?? '0.00' }}" />
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Subtotal') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="{{ setting('currency', '$') }}{{ $selectedModel->sub_total ?? '' }}" />
        </div>
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Discount Amount') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="-{{ setting('currency', '$') }}{{ $selectedModel->discount ?? '' }}" />
        </div>
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Delivery Fee') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="+{{ setting('currency', '$') }}{{ $selectedModel->delivery_fee ?? '' }}" />
        </div>
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Tax') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="+{{ setting('currency', '$') }}{{ $selectedModel->tax ?? '' }}" />
        </div>
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Total') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="{{ setting('currency', '$') }}{{ $selectedModel->total ?? '' }}" />
        </div>
    </div>
</div>

resources/views/livewire/order/regular_order_details.blade.php
<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">

    <x-details.item title="{{ __('Code') }}"
        text="#{{ $selectedModel->code ?? '' }}" />
    <x-details.item title="{{ __('Status') }}"
        text="{{ $selectedModel->status ?? '' }}" />
    <x-details.item title="{{ __('Payment Status') }}"
        text="{{ $selectedModel->payment_status ?? '' }}" />
    <x-details.item title="{{ __('Payment Method') }}"
        text="{{ $selectedModel->payment_method->name ?? '' }}" />
</div>
<div class="grid grid-cols-1 gap-4 mt-5 border-t md:grid-cols-2 lg:grid-cols-3">
    <x-details.item
        title="{{ $selectedModel != null && $selectedModel->is_package ? __('Sender')  : __('User') }}"
        text="{{ $selectedModel->user->name ?? '' }}" />
    <x-details.item
        title="{{ $selectedModel != null && $selectedModel->is_package ? __('Sender Phone')  : __('User Phone') }}"
        text="{{ $selectedModel->user->phone ?? '' }}" />

    {{-- Pickup address --}}
    @if(!empty($selectedModel->delivery_address))
        <x-details.item title="{{ __('Delivery Address') }}"
            text="{{ $selectedModel->delivery_address->address ?? '' }}" />
    @else
        <x-details.item title="{{ __('Delivery Address') }}"
            text="{{ __('Customer Self Pickup') }}" />
    @endif

</div>
<div class="mt-5 border-t">
        <x-details.item title="{{ __('Note') }}"
        text="{{ $selectedModel->note ?? '--' }}" />
</div>
<div class="grid grid-cols-1 gap-4 mt-5 border-t md:grid-cols-2 lg:grid-cols-3">

    <x-details.item title="{{ __('Vendor') }}"
        text="{{ $selectedModel->vendor->name ?? '' }}" />
    <x-details.item title="{{ __('Vendor Address') }}"
        text="{{ $selectedModel->vendor->address ?? '' }}" />


    <x-details.item title="{{ __('Date of order') }}"
        text="{{ $selectedModel != null ? $selectedModel->created_at->format('M d, Y \\a\\t H:i a') : '' }}" />
    <x-details.item title="{{ __('Updated At') }}"
    text="{{ $selectedModel != null ? $selectedModel->updated_at->format('M d, Y \\a\\t H:i a') : '' }}" />
</div>

{{-- driver info --}}
<div class="grid grid-cols-1 gap-4 pt-4 mt-4 border-t md:grid-cols-2 lg:grid-cols-3">
    <x-details.item title="{{ __('Driver') }}"
        text="{{ $selectedModel->driver->name ?? '--' }}" />
    <x-details.item title="{{ __('Driver Phone') }}"
        text="{{ $selectedModel->driver->phone ?? '--' }}" />
</div>

{{-- foods --}}
<div class="pt-4 mt-4 border-t ">
    <x-order.products :products="$selectedModel->products ?? ''" />
</div>

{{-- order photo --}}
@if($selectedModel != null && $selectedModel->photo && !strpos($selectedModel->photo, 'default.png') )
<p class="mt-8 font-bold text-md">Order Photo</p>
    <a href="{{ $selectedModel->photo }}" target="_blank"> <img src="{{ $selectedModel->photo }}" class="w-56 h-56 rounded-sm" /></a>
@endif

{{-- money --}}
<div class="pt-4 border-t justify-items-end">

    <div class="flex items-center justify-start p-4 space-x-20 border-2">
        <p class="my-auto">
            {{-- <x-label title="Driver Tip" /> --}}
            {{ __('Driver Tip') }}
        </p>
        <x-details.p
            text="{{ setting('currency', '$') }}{{ $selectedModel->tip ?? '0.00' }}" />
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Subtotal') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="{{ setting('currency', '$') }}{{ $selectedModel->sub_total ?? '' }}" />
        </div>
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Discount Amount') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="-{{ setting('currency', '$') }}{{ $selectedModel->discount ?? '' }}" />
        </div>
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Delivery Fee') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="+{{ setting('currency', '$') }}{{ $selectedModel->delivery_fee ?? '' }}" />
        </div>
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Tax') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="+{{ setting('currency', '$') }}{{ $selectedModel->tax ?? '' }}" />
        </div>
    </div>
    <div class="flex items-center justify-end space-x-20 border-b">
        <x-label title="{{ __('Total') }}" />
        <div class="w-6/12 md:w-4/12 lg:w-2/12">
            <x-details.p
                text="{{ setting('currency', '$') }}{{ $selectedModel->total ?? '' }}" />
        </div>
    </div>
</div>